Repository go-xorm/builder, pull requests merged in 2018-08, with the labels that each got.

#18 builder feature: union
  README.md
  builder.go
  builder_union.go
  builder_union_test.go
Labels: feature

#21 Add bindedSQL support
  builder.go
  builder_test.go
  cond.go
  error.go
  sql.go
  sql_test.go
Labels: feature

#23 add more join tests
  builder_select_test.go
  builder_test.go
  sql.go
  sql_test.go
Labels: testing

#24 add more tests for update
  builder.go
  builder_delete.go
  builder_insert.go
  builder_select.go
  builder_test.go
  builder_update.go
  builder_update_test.go
  error.go
Labels: testing

#25 More update tests
  builder_update_test.go
Labels: testing

#27 More tests
  builder_insert.go
  builder_select.go
  builder_select_test.go
  builder_test.go
  builder_union.go
  builder_union_test.go
  error.go
Labels: testing

#28 between support Expr and more tests
  builder_test.go
  cond_between.go
Labels: enhancement, testing

#30 Rewrite From
  builder.go
  builder_b_test.go
  builder_limit.go
  builder_limit_test.go
  builder_select.go
  builder_select_test.go
  builder_union.go
  error.go
  sql_test.go
Labels: enhancement, testing

#31 more tests
  builder.go
  builder_test.go
  cond_test.go
  sql_test.go
  string_builder.go
  string_builder_test.go
Labels: testing

#32 more tests
  builder_insert.go
  builder_test.go
  string_builder_test.go
Labels: testing

#35 Update From & more tests
  builder.go
  builder_b_test.go
  builder_select.go
  builder_select_test.go
  builder_union.go
  builder_union_test.go
  error.go
  sql.go
  sql_test.go
Labels: enhancement
